version: '3.9'


services:

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://host.docker.internal:5432/bd'
      APP_IMAGE_BUCKET: images/
      APP_REPORT_GENERATOR_HOST: report_service
    depends_on:
      - report_service

  report_service:
    restart: always
    build:
#      context: ./reportgenerator
      context: ./reportservice
      dockerfile: Dockerfile
    hostname: report_service
