version: '3.9'


services:

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://host.docker.internal:5432/bd'
      APP_IMAGE_BUCKET: images_service
      APP_REPORT_GENERATOR_HOST: report_service
      APP_REPORT_GENERATOR_PORT: 5488
      APP_REPORT_GENERATOR_ROUTE: '/api/v1/generator/generate'
      APP_IMAGE_BUCKET_SOURCE: images_service
      APP_IMAGE_BUCKET_PORT: 8888
      APP_IMAGE_BUCKET_LOCAL: false
    depends_on:
      - report_service
      - images_service

  report_service:
    restart: always
    build:
      context: ./reportservice
      dockerfile: Dockerfile
    hostname: report_service

  images_service:
    image: nginx:stable-alpine3.20-perl
    restart: always
    expose:
      - 8888
    #    ports:
    #      - "127.0.0.1:8888:8888"
    volumes:
      - ./images/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./images/postimages:/var/opt/postimages
      - ./images/profileimages:/var/opt/profileimages
    hostname: images_service