spring:application:name: bd

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: create
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

app:
  image:
    bucket: src/images
  report:
    bucket: reports
#    bucket: C:\Users\egor\IdeaProjects\bd\src\images
