#spring:application:name: bd

spring:
  application:
    name: bd
  datasource:
    url: jdbc:postgresql://localhost:5432/bd
#    url: jdbc:postgresql://host.docker.internal:5432/bd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: false
      format_sql: true
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    async:
      request-timeout: -1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#  data:
#    jdbc:
#      dialect: postgresql

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

app:
  image:
    bucket:
      source: images
      local: true
      port: null
  report:
#    bucket: reports
    generator:
      port: 5488
      host: localhost
      route: /api/v1/generator/generate

